### ISSUE TITLE
Add palestrantes 2019

### ISSUE THREAD

**Issue by alessandrofeitoza** [PHPcomRapadura/conference-website#21]
- Adiel Cristo (convidado)
 - Carol Rodrigues
 - Chicão Thiago
 - Ian Rodrigues
 - Juliana Martins
 - Luítame de Oliveira
 - Raquel Barra

**Comment by Luitame** [comment]
## Adiel Cristo
![Adiel](https://user-images.githubusercontent.com/5892371/68815384-080b4100-065a-11ea-95fb-e7c74beb8b7b.jpg)

**Salvador-BA**

Desenvolvedor Web com 16 anos de experiência, trabalhando principalmente com PHP e Java. Apaixonado por PHP e DevOps, vive aprendendo sobre a linguagem e sobre metodologias e ferramentas relacionadas, e procurando formas de retribuir à comunidade.

**Github:** https://github.com/adielcristo
**Twitter:** https://twitter.com/adielcristo
**Facebook:** https://www.facebook.com/adiel.cristo

**Comment by Luitame** [comment]
## Carol Rodrigues
![Carol](https://user-images.githubusercontent.com/5892371/68815543-72bc7c80-065a-11ea-8044-db535bfb3c66.jpg)

**Fortaleza-CE**

Tester, Desenvolvedora Front-End Jr., Representante das comunidades PHPWomenCE e Front-end CE, estudante de Análise e Desenvolvimento de Sistemas.

**Twitter:** https://twitter.com/caroline_rp22
**Facebook:** https://www.facebook.com/annecaroline222
**Github:**

**Comment by Luitame** [comment]
## Ian Rodrigues

![Ian Rodrigues](https://user-images.githubusercontent.com/5892371/68815739-00986780-065b-11ea-9f0d-50bb83aaa550.jpg)

**Fortaleza-CE**

Programador (e palestrante) experiente, que foca em um código limpo e que entrega valor. Gosto de compartilhar conhecimento e me preocupo com o auto-aperfeiçoamento. Gosto de palestrar em conferências e meetups sobre PHP, clean code, testes automatizados, infraestrutura e muito mais.

**Twitter:** https://twitter.com/ianrdrgs
**Github:** https://github.com/ianrodrigues

**Comment by Luitame** [comment]
## Juliana Martins

![Juliana](https://user-images.githubusercontent.com/5892371/68815847-5b31c380-065b-11ea-9bbc-e2e546c58456.jpg)

**Fortaleza-CE**

Gerente de Projetos na OSF Global

**Facebook:** https://www.facebook.com/juliana.martinsdeoliveira.31
**Github:** https://github.com/jullianamartins
**Twitter:** https://twitter.com/jullianamar

**Comment by Luitame** [comment]
## Raquel Barra

![Raquel](https://user-images.githubusercontent.com/5892371/68815978-c67b9580-065b-11ea-9b6b-cc10f286a5cf.jpg)

**Fortaleza-CE**

Técnica em Informática. Graduanda de Sistemas para Internet. Participante das comunidades PHP com Rapadura, FrontEnd CE, Darkmira Tour. Representante da Comunidade PHPWomen CE. Líder do Casulo (Grupo de Estudo Faculdade Evolução). Entusiasta do PHP.

**Facebook:** https://www.facebook.com/raquelsantosbarra
**Twitter:** https://twitter.com/labarraquel
**Github:** https://github.com/rsb12php

**Comment by Luitame** [comment]
## Chicão Thiago

![Chicão](https://user-images.githubusercontent.com/5892371/68816554-92a16f80-065d-11ea-8bc8-c3b1d45487ae.jpg)

**Fortaleza-CE**

Sou desenvolvedor web à mais ou menos 3 anos. Trabalho atualmente com Laravel desde a versão 4 até projetos na versão 6, Vuejs nas telas e salvando tudo que presta e não presta em uns NoSql e alguns SQL da vida. Mestrando em Ciência da Computação com foco em Microsserviços e auto-adaptação.

**Twitter:** https://twitter.com/chicaothiago
**Github:** https://github.com/chicaothiago
**Facebook:** https://www.facebook.com/fthiagogv

**Comment by Luitame** [comment]
## Luítame de Oliveira

![Luítame](https://user-images.githubusercontent.com/5892371/68817153-8c13f780-065f-11ea-95fa-b0a3719c6404.jpeg)

Backend developer at Oowlish

**Twitter:** https://twitter.com/luitame
**Github:** https://github.com/luitame
**Facebook:** https://www.facebook.com/luitame
