### ISSUE TITLE
Add 2019 Schedule

### ISSUE THREAD

**Issue by alessandrofeitoza** [PHPcomRapadura/conference-website#23]

**Comment by Luitame** [comment]
![image](https://user-images.githubusercontent.com/5892371/68820870-6f7dbc80-066b-11ea-8288-d17f6e07aeb6.png)

Eu fiz o PR acima com o rascunho da programação do evento. Por favor, atualiza a ordem e os horários.

**Comment by Luitame** [comment]
![image](https://user-images.githubusercontent.com/5892371/68860276-fbbdcd00-06c7-11ea-8ce0-eb7e30b407d0.png)

Atualizado, please @alessandrofeitoza revisar!
